use crate::include::ctype::*;

pub const MEMBARRIER_CMD_QUERY: c_int = 0;
pub const MEMBARRIER_CMD_GLOBAL: c_int = 1;
pub const MEMBARRIER_CMD_GLOBAL_EXPEDITED: c_int = 2;
pub const MEMBARRIER_CMD_REGISTER_GLOBAL_EXPEDITED: c_int = 4;
pub const MEMBARRIER_CMD_PRIVATE_EXPEDITED: c_int = 8;
pub const MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED: c_int = 16;
pub const MEMBARRIER_CMD_PRIVATE_EXPEDITED_SYNC_CORE: c_int = 32;
pub const MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED_SYNC_CORE: c_int = 64;
pub const MEMBARRIER_CMD_PRIVATE_EXPEDITED_RSEQ: c_int = 128;
pub const MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED_RSEQ: c_int = 256;

pub const MEMBARRIER_CMD_SHARED: c_int = MEMBARRIER_CMD_GLOBAL;